THEME_SCHEME=gruvbox
THEME_MODE=dark
THEME_VARIANT=medium
THEME_NVIM=gruvbox
THEME_NVIM_BG=dark
THEME_GHOSTTY="Gruvbox Dark"
THEME_PALETTE=gruvbox-dark
THEME_FSH=gruvbox-dark
THEME_EZA=gruvbox-dark
THEME_BTOP=gruvbox-dark
THEME_FZF=gruvbox-dark
THEME_BAT="gruvbox-dark"
