THEME_SCHEME=tokyonight
THEME_MODE=dark
THEME_VARIANT=moon
THEME_NVIM=tokyonight-moon
THEME_NVIM_BG=dark
THEME_GHOSTTY="TokyoNight Moon"
THEME_PALETTE=tokyonight-moon
THEME_FSH=tokyonight-moon
THEME_EZA=tokyonight-moon
THEME_BTOP=tokyonight-moon
THEME_FZF=tokyonight-moon
THEME_BAT="tokyonight_moon"
