return {
  {
    "esmuellert/codediff.nvim",
    cmd = "CodeDiff",
    keys = {
      { "<leader>gcd", "<cmd>CodeDiff<cr>", desc = "Show git diff" },
      { "<leader>gch", "<cmd>CodeDiff history<cr>", desc = "Show git history" },
      { "<leader>gcf", "<cmd>CodeDiff history %<cr>", desc = "Show git file history" },
      { "<leader>gcl", "<cmd>'<,'>CodeDiff history<cr>", desc = "Show git line history", mode = { "n", "x" } },
    },
    opts = {
      keys = {
        view = {
          next_hunk = "]h",
          prev_hunk = "[h",
        },
      },
    },
  },
  {
    "pwntester/octo.nvim",
    opts = {
      -- Rebind every default <localleader> in-buffer mapping to <leader>go.
      -- Only lhs is overridden; octo deep-merges these over its defaults, so
      -- descriptions and modes come from the plugin.
      mappings = {
        discussion = {
          add_comment = { lhs = "<leader>goca" },
          add_reply = { lhs = "<leader>gocr" },
          delete_comment = { lhs = "<leader>gocd" },
          comment_edits = { lhs = "<leader>goce" },
          reference_in_new_issue = { lhs = "<leader>gori" },
          add_label = { lhs = "<leader>gola" },
          remove_label = { lhs = "<leader>gold" },
          next_comment = { lhs = "<leader>goc]" },
          prev_comment = { lhs = "<leader>goc[" },
          react_hooray = { lhs = "<leader>gorp" },
          react_heart = { lhs = "<leader>gorh" },
          react_eyes = { lhs = "<leader>gore" },
          react_thumbs_up = { lhs = "<leader>gor+" },
          react_thumbs_down = { lhs = "<leader>gor-" },
          react_rocket = { lhs = "<leader>gorr" },
          react_laugh = { lhs = "<leader>gorl" },
          react_confused = { lhs = "<leader>gorc" },
        },
        issue = {
          close_issue = { lhs = "<leader>goic" },
          reopen_issue = { lhs = "<leader>goio" },
          list_issues = { lhs = "<leader>goil" },
          add_assignee = { lhs = "<leader>goaa" },
          remove_assignee = { lhs = "<leader>goad" },
          create_label = { lhs = "<leader>golc" },
          add_label = { lhs = "<leader>gola" },
          remove_label = { lhs = "<leader>gold" },
          goto_issue = { lhs = "<leader>gogi" },
          add_comment = { lhs = "<leader>goca" },
          add_reply = { lhs = "<leader>gocr" },
          delete_comment = { lhs = "<leader>gocd" },
          comment_edits = { lhs = "<leader>goce" },
          reference_in_new_issue = { lhs = "<leader>gori" },
          next_comment = { lhs = "<leader>goc]" },
          prev_comment = { lhs = "<leader>goc[" },
          react_hooray = { lhs = "<leader>gorp" },
          react_heart = { lhs = "<leader>gorh" },
          react_eyes = { lhs = "<leader>gore" },
          react_thumbs_up = { lhs = "<leader>gor+" },
          react_thumbs_down = { lhs = "<leader>gor-" },
          react_rocket = { lhs = "<leader>gorr" },
          react_laugh = { lhs = "<leader>gorl" },
          react_confused = { lhs = "<leader>gorc" },
        },
        pull_request = {
          checkout_pr = { lhs = "<leader>gopo" },
          merge_pr = { lhs = "<leader>gopm" },
          squash_and_merge_pr = { lhs = "<leader>gopsm" },
          rebase_and_merge_pr = { lhs = "<leader>goprm" },
          merge_pr_queue = { lhs = "<leader>gopq" },
          squash_and_merge_queue = { lhs = "<leader>gopsq" },
          rebase_and_merge_queue = { lhs = "<leader>goprq" },
          list_commits = { lhs = "<leader>gopc" },
          list_changed_files = { lhs = "<leader>gopf" },
          show_pr_diff = { lhs = "<leader>gopd" },
          add_reviewer = { lhs = "<leader>gova" },
          remove_reviewer = { lhs = "<leader>govd" },
          close_issue = { lhs = "<leader>goic" },
          reopen_issue = { lhs = "<leader>goio" },
          list_issues = { lhs = "<leader>goil" },
          add_assignee = { lhs = "<leader>goaa" },
          remove_assignee = { lhs = "<leader>goad" },
          create_label = { lhs = "<leader>golc" },
          add_label = { lhs = "<leader>gola" },
          remove_label = { lhs = "<leader>gold" },
          goto_issue = { lhs = "<leader>gogi" },
          add_comment = { lhs = "<leader>goca" },
          add_reply = { lhs = "<leader>gocr" },
          delete_comment = { lhs = "<leader>gocd" },
          comment_edits = { lhs = "<leader>goce" },
          reference_in_new_issue = { lhs = "<leader>gori" },
          next_comment = { lhs = "<leader>goc]" },
          prev_comment = { lhs = "<leader>goc[" },
          react_hooray = { lhs = "<leader>gorp" },
          react_heart = { lhs = "<leader>gorh" },
          react_eyes = { lhs = "<leader>gore" },
          react_thumbs_up = { lhs = "<leader>gor+" },
          react_thumbs_down = { lhs = "<leader>gor-" },
          react_rocket = { lhs = "<leader>gorr" },
          react_laugh = { lhs = "<leader>gorl" },
          react_confused = { lhs = "<leader>gorc" },
          review_start = { lhs = "<leader>govs" },
          review_resume = { lhs = "<leader>govr" },
          resolve_thread = { lhs = "<leader>gort" },
          unresolve_thread = { lhs = "<leader>gorT" },
          approve_pr = { lhs = "<leader>goqa" },
        },
        review_thread = {
          goto_issue = { lhs = "<leader>gogi" },
          add_comment = { lhs = "<leader>goca" },
          add_reply = { lhs = "<leader>gocr" },
          add_suggestion = { lhs = "<leader>gosa" },
          delete_comment = { lhs = "<leader>gocd" },
          comment_edits = { lhs = "<leader>goce" },
          reference_in_new_issue = { lhs = "<leader>gori" },
          next_comment = { lhs = "<leader>goc]" },
          prev_comment = { lhs = "<leader>goc[" },
          react_hooray = { lhs = "<leader>gorp" },
          react_heart = { lhs = "<leader>gorh" },
          react_eyes = { lhs = "<leader>gore" },
          react_thumbs_up = { lhs = "<leader>gor+" },
          react_thumbs_down = { lhs = "<leader>gor-" },
          react_rocket = { lhs = "<leader>gorr" },
          react_laugh = { lhs = "<leader>gorl" },
          react_confused = { lhs = "<leader>gorc" },
          resolve_thread = { lhs = "<leader>gort" },
          unresolve_thread = { lhs = "<leader>gorT" },
        },
        review_diff = {
          submit_review = { lhs = "<leader>govs" },
          discard_review = { lhs = "<leader>govd" },
          add_review_comment = { lhs = "<leader>goca" },
          add_review_suggestion = { lhs = "<leader>gosa" },
          focus_files = { lhs = "<leader>goe" },
          toggle_files = { lhs = "<leader>gob" },
          toggle_viewed = { lhs = "<leader>go<space>" },
          review_commits = { lhs = "<leader>goC" },
        },
        file_panel = {
          submit_review = { lhs = "<leader>govs" },
          discard_review = { lhs = "<leader>govd" },
          focus_files = { lhs = "<leader>goe" },
          toggle_files = { lhs = "<leader>gob" },
          toggle_viewed = { lhs = "<leader>go<space>" },
          review_commits = { lhs = "<leader>goC" },
        },
        notification = {
          read = { lhs = "<leader>gonr" },
          done = { lhs = "<leader>gond" },
          unsubscribe = { lhs = "<leader>gonu" },
        },
        repo = {
          create_issue = { lhs = "<leader>goic" },
          create_discussion = { lhs = "<leader>godc" },
          contributing_guidelines = { lhs = "<leader>gocg" },
        },
      },
    },
    keys = {
      -- Clear the LazyVim octo extra's now-orphaned <localleader> group headers.
      { "<localleader>a", false },
      { "<localleader>c", false },
      { "<localleader>l", false },
      { "<localleader>i", false },
      { "<localleader>r", false },
      { "<localleader>p", false },
      { "<localleader>pr", false },
      { "<localleader>ps", false },
      { "<localleader>v", false },
      { "<localleader>g", false },

      -- Move the extra's global launchers off <leader>g* (frees them for
      -- snacks.nvim git commands) and re-home them under <leader>gol*.
      { "<leader>gi", false },
      { "<leader>gI", false },
      { "<leader>gp", false },
      { "<leader>gP", false },
      { "<leader>gr", false },
      { "<leader>gS", false },
      { "<leader>goli", "<cmd>Octo issue list<CR>", desc = "List Issues (Octo)" },
      { "<leader>golI", "<cmd>Octo issue search<CR>", desc = "Search Issues (Octo)" },
      { "<leader>golp", "<cmd>Octo pr list<CR>", desc = "List PRs (Octo)" },
      { "<leader>golP", "<cmd>Octo pr search<CR>", desc = "Search PRs (Octo)" },
      { "<leader>golr", "<cmd>Octo repo list<CR>", desc = "List Repos (Octo)" },
      { "<leader>gols", "<cmd>Octo search<CR>", desc = "Search (Octo)" },
    },
  },
  {
    "folke/snacks.nvim",
    -- Re-enable the snacks git/GitHub pickers the octo extra disabled.
    keys = {
      {
        "<leader>gi",
        function()
          Snacks.picker.gh_issue()
        end,
        desc = "GitHub Issues (open)",
      },
      {
        "<leader>gI",
        function()
          Snacks.picker.gh_issue({ state = "all" })
        end,
        desc = "GitHub Issues (all)",
      },
      {
        "<leader>gp",
        function()
          Snacks.picker.gh_pr()
        end,
        desc = "GitHub Pull Requests (open)",
      },
      {
        "<leader>gP",
        function()
          Snacks.picker.gh_pr({ state = "all" })
        end,
        desc = "GitHub Pull Requests (all)",
      },
    },
  },
}
