# enable mouse mode
set -g mouse on

# use colors
set -g default-terminal tmux-256color
set -as terminal-features ",xterm-256color:RGB:usstyle"
set -as terminal-overrides ',xterm-256color:Setulc=\E[58\0722\072\072%p1%{65536}%/%d\072%p1%{256}%/%{255}%&%d\072%p1%{255}%&%d%;m'

# enable vi mode
set -g mode-keys vi
set -g status-keys vi
set -g escape-time 10

# disable default clipboard support use an external command below
set -g set-clipboard off

# automatically renumber windows so no gaps appear
set -g renumber-windows on

# start windows and pane indexing from 1
set -g base-index 1
set -g pane-base-index 1
