# plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'IngoMeyer441/tmux-easy-motion'
set -g @plugin 'Morantron/tmux-fingers'

set -g @yank_with_mouse off

# easy motion
set -g @easy-motion-prefix-enabled false
set -g @easy-motion-copy-mode-prefix 'M-s'
set -g @easy-motion-copy-mode-prefix-enabled true
set -g @easy-motion-default-motion 'bd-f2'

# fingers
set -g @fingers-pattern-0 "arn:aws:[^\s]+"

# tmux vim navigator
set -g @vim_navigator_mapping_left "C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""
set -g @tmux_navigator_disable_when_zoomed "1"
